# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ApiResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, winner=None):  # noqa: E501
        """ApiResponse - a model defined in OpenAPI

        :param winner: The winner of this ApiResponse.  # noqa: E501
        :type winner: int
        """
        self.openapi_types = {
            'winner': int
        }

        self.attribute_map = {
            'winner': 'winner'
        }

        self._winner = winner

    @classmethod
    def from_dict(cls, dikt) -> 'ApiResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApiResponse of this ApiResponse.  # noqa: E501
        :rtype: ApiResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def winner(self):
        """Gets the winner of this ApiResponse.


        :return: The winner of this ApiResponse.
        :rtype: int
        """
        return self._winner

    @winner.setter
    def winner(self, winner):
        """Sets the winner of this ApiResponse.


        :param winner: The winner of this ApiResponse.
        :type winner: int
        """

        self._winner = winner
